# Generated by Django 3.2.5 on 2022-06-09 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='admin',
            new_name='is_superuser',
        ),
    ]
