# Generated by Django 3.2.5 on 2022-06-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_admin_userinfo_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='mobile',
            field=models.IntegerField(default=False, verbose_name='手机号码'),
        ),
    ]
